### PR TITLE
Implement GetById in the PollutedLocationController

### LINKED ISSUE #30: Implement GetById in the PollutedLocationController
## Prerequisites

This task requires #29 to be finished, do not start it before that.

## Description

Implement a new `GetById` method for the `PollutedLocationController`, which would take the id as a parameter (from URI)

## Steps to take

1. Create one GET action/endpoint at route `/Api/PollutedLocation/{Id}` that returns a single PollutedLocationDTO object.
2. Use the repository method `GetByIdAsync`.
3. Use different ActionResults `Not Found` and `Ok`.

## Acceptance criteria

Endpoint is reachable at `/Api/PollutedLocation/{Id}` and this action is seen in swagger. Given an existent id it would return a PollutedLocation instance and if there was no PollutedLocation object found - `Not found` ActionResult with the message `PollutedLocation with the specified id {id} was not found.`

### PR DESCRIPTION
**Pull request by 6ar8nas**
## What was done

- One GET action/endpoint at route /Api/PollutedLocation/{Id} created using the repository's GetByIdAsync method
- Different ActionResults returned depending on the outcome of the GetByIdAsync call

### CODE REVIEW

**Comment by BaVilius** [comment]
**LGTM**

**Review by BenasB — APPROVED** [review]
Would it be possible for you to write unit tests for this? Using [`Moq`](https://github.com/moq/moq4) you could mock the `_repository` and write some test cases when this returns 200, 404, etc

**Comment by BenasB** [comment]
Action LGTM btw

**Comment by 6ar8nas** [comment]
> Would it be possible for you to write unit tests for this? Using [`Moq`](https://github.com/moq/moq4) you could mock the `_repository` and write some test cases when this returns 200, 404, etc

#33 Created a new issue regarding this.

**Pull request merged**
